CREATE TABLE ds_user (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(500),
    EMAIL VARCHAR(255),
    RESET_PASSWORD_TOKEN VARCHAR(500),
    ACCOUNT_VERIFICATION_TOKEN VARCHAR(500),
    ACCOUNT_VERIFIED BOOLEAN,
    PASSWORD_HASH VARCHAR(500)
);

CREATE TABLE ds_user_role (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    USER_ROLE VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES ds_user(ID)
);

CREATE TABLE ds_user_active_session (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    TOKEN VARCHAR(750),
    VALIDITY TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES ds_user(ID)
);

CREATE TABLE ds_address (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(10),
    LINE_ONE VARCHAR(100),
    LINE_TWO VARCHAR(100),
    TOWN_OR_CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    PIN_CODE VARCHAR(10)
);

CREATE TABLE ds_person (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(500),
    EMAIL VARCHAR(255),
    MOBILE_NUMBER VARCHAR(15),
    DATE_OF_BIRTH DATE,
    COUNTRY VARCHAR(50)
);

CREATE TABLE ds_person_address (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID INT,
    ADDRESS_ID INT,
    FOREIGN KEY (PERSON_ID) REFERENCES ds_person(ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ds_address(ID)
);

CREATE TABLE ds_organization (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(500),
    EMAIL VARCHAR(255),
    MOBILE_NUMBER VARCHAR(15),
    CONTACT_NUMBER VARCHAR(15),
    COUNTRY VARCHAR(50)
);

CREATE TABLE ds_organization_address (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZATION_ID INT,
    ADDRESS_ID INT,
    TYPE VARCHAR(10),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ds_organization(ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ds_address(ID)
);

/*  References ds_person,  id = ds_person.id */
CREATE TABLE ds_director (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZATION_ID INT,
    STATUS VARCHAR(10),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ds_organization(ID)
);

/*  References ds_person,  id = ds_person.id */
CREATE TABLE ds_pilot (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_OWNER_ID INT,
    STATUS VARCHAR(10),
    DRONE_CATEGORY VARCHAR(20),
    TRAINING_CERTIFICATE_DOC_NAME VARCHAR(200)
);

/*  References ds_person,  id = ds_person.id */
CREATE TABLE ds_individual_operator (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_OWNER_ID INT,
    STATUS VARCHAR(10)
);


/*  References ds_organization,  id = ds_organization.id */
CREATE TABLE ds_organization_operator (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_OWNER_ID INT,
    STATUS VARCHAR(10)
);



