CREATE TABLE yourtable
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SECOND_CHAR  VARCHAR(1),
    THIRD_CHAR   VARCHAR(1),
    FOURTH_FIFTH_SIXTH_NUM   INT,
    SEVENTH_NUMBER TINYINT,
    ASSIGNED_FLY_PERMISSION_ID VARCHAR(30),
    CREATED_TIMESTAMP TIMESTAMP,
    VALID_FOR_DATE DATE,
    ADC_NUMBER VARCHAR(7)
    PRIMARY KEY (ADC_NUMBER,VALID_FOR_DATE)
)