CREATE TABLE ds_fic_number
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_TO_FIFTH_NUMBERS   INT,
    LAST_CHAR VARCHAR(1),
    ASSIGNED_FLY_PERMISSION_ID VARCHAR(30),
    CREATED_TIMESTAMP TIMESTAMP,
    VALID_FOR_DATE DATE,
    FIC_NUMBER VARCHAR(7),
    CONSTRAINT pk_fic_date UNIQUE (FIC_NUMBER,VALID_FOR_DATE)
)